set -e fish_user_paths

# homebrew autogenerated
set --global --export HOMEBREW_PREFIX "/opt/homebrew";
set --global --export HOMEBREW_CELLAR "/opt/homebrew/Cellar";
set --global --export HOMEBREW_REPOSITORY "/opt/homebrew";
fish_add_path --global --move --path "/opt/homebrew/bin" "/opt/homebrew/sbin";
if test -n "$MANPATH[1]"; set --global --export MANPATH '' $MANPATH; end;
if not contains "/opt/homebrew/share/info" $INFOPATH; set --global --export INFOPATH "/opt/homebrew/share/info" $INFOPATH; end;

# go 
set -x GOPATH $HOME/.go
set -x PATH $PATH $GOPATH/bin

# rust
set -g fish_user_paths $HOME/.cargo/bin $fish_user_paths

# bun
set -x BUN_INSTALL "$HOME/.bun"
set -gx PATH "$BUN_INSTALL/bin" $PATH

# uv
set -gx PATH "$HOME/.local/bin" $PATH

# jdk
set -gx PATH "/opt/homebrew/opt/openjdk@21/bin" $PATH