# homebrew autogenerated
set --global --export HOMEBREW_PREFIX "/opt/homebrew"
set --global --export HOMEBREW_CELLAR "/opt/homebrew/Cellar"
set --global --export HOMEBREW_REPOSITORY "/opt/homebrew"

if test -d /opt/homebrew/bin
	fish_add_path --global --move /opt/homebrew/bin
end

if test -d /opt/homebrew/sbin
	fish_add_path --global --move /opt/homebrew/sbin
end

if test -n "$MANPATH[1]"
	set --global --export MANPATH '' $MANPATH
end

if not contains "/opt/homebrew/share/info" $INFOPATH
	set --global --export INFOPATH "/opt/homebrew/share/info" $INFOPATH
end

# go 
set -gx GOPATH "$HOME/.go"
if test -d "$GOPATH/bin"
	fish_add_path --global "$GOPATH/bin"
end

# rust
if test -d "$HOME/.cargo/bin"
	fish_add_path --global "$HOME/.cargo/bin"
end

# bun
set -gx BUN_INSTALL "$HOME/.bun"
if test -d "$BUN_INSTALL/bin"
	fish_add_path --global "$BUN_INSTALL/bin"
end

# uv
if test -d "$HOME/.local/bin"
	fish_add_path --global "$HOME/.local/bin"
end

# jdk
if test -d "/opt/homebrew/opt/openjdk@21/bin"
	fish_add_path --global "/opt/homebrew/opt/openjdk@21/bin"
end